In [ ]:
#NumPy

In [ ]:
%pip install numpy

In [ ]:
import numpy as np

In [ ]:
# creating Arrays

In [ ]:
sample_array = np.array([1,2,3,4])

In [ ]:
sample_array

array([1, 2, 3, 4])

In [ ]:
#2D Array(Matrix)

In [ ]:
sample_array2 = np.array([[1,2],[3,4]])

In [ ]:
sample_array2

array([[1, 2],
       [3, 4]])

In [ ]:
#3D(Tensor)

In [ ]:
sample_array3 = np.array([[[1,2],[3,4]],[[6,7],[6,0]]])

In [ ]:
sample_array3

array([[[1, 2],
        [3, 4]],

       [[6, 7],
        [6, 0]]])

In [ ]:
# Dimensions
#0-D(Scalar) - Single Number
# 1-D(Vector) - List
# 2-D(Matrix) - A table with rows and columns
# 3-D(Tensor) - A stack of Tables

In [ ]:
sample_array = np.array([[[34,56],[67,98]],[[43,95],[89,43]]])

In [ ]:
sample_array

array([[[34, 56],
        [67, 98]],

       [[43, 95],
        [89, 43]]])

In [ ]:
# Array Properties

In [ ]:
sample_array2 = np.array([[34,45],[67,98]])

In [ ]:
sample_array2

array([[34, 45],
       [67, 98]])

In [ ]:
#shape

In [ ]:
sample_array2.shape

(2, 2)

In [ ]:
sample_array2.ndim

2

In [ ]:
sample_array2.size

4

In [ ]:
sample_array2.dtype

dtype('int64')

In [ ]:
sample3= np.array([[[34,56],[67,98]],[[56,90],[23,78]]])

In [ ]:
sample3

array([[[34, 56],
        [67, 98]],

       [[56, 90],
        [23, 78]]])

In [ ]:
sample3.shape

(2, 2, 2)

In [ ]:
sample3.ndim

3

In [ ]:
sample3.dtype

dtype('int64')

In [ ]:
sample3.size

8

In [ ]:
sample2_array = np.array([[0,0,0],[0,0,0]])

In [ ]:
sample2_array

array([[0, 0, 0],
       [0, 0, 0]])

In [ ]:
sample2_array = np.array([[1,1,1],[1,1,1]])

In [ ]:
sample2_array

array([[1, 1, 1],
       [1, 1, 1]])

In [ ]:
# Specials arrays

In [ ]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [ ]:
np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [ ]:
np.arange(0,10,2)

array([0, 2, 4, 6, 8])

In [ ]:
np.arange(0,100,3)

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27, 30, 33, 36, 39, 42, 45, 48,
       51, 54, 57, 60, 63, 66, 69, 72, 75, 78, 81, 84, 87, 90, 93, 96, 99])

In [ ]:
# Array Operations

In [ ]:
Array_A=np.array([1,2,3,4,5])
Array_B=np.array([6,7,8,9,0])

In [ ]:
Array_A

array([1, 2, 3, 4, 5])

In [ ]:
Array_B

array([6, 7, 8, 9, 0])

In [ ]:
Array_A + Array_B

array([ 7,  9, 11, 13,  5])

In [ ]:
Array_A - Array_B

array([-5, -5, -5, -5,  5])

In [ ]:
Array_A * Array_B

array([ 6, 14, 24, 36,  0])

In [ ]:
Array_A / Array_B

/tmp/ipykernel_2869/4100675645.py:1: RuntimeWarning: divide by zero encountered in divide
  Array_A / Array_B


array([0.16666667, 0.28571429, 0.375     , 0.44444444,        inf])

In [ ]:
#mathematical function

In [ ]:
A1=np.array([1,4,9])

In [ ]:
A1

array([1, 4, 9])

In [ ]:
np.sqrt(A1)

array([1., 2., 3.])

In [ ]:
np.sqrt(27)

np.float64(5.196152422706632)

In [ ]:
np.log(0)

/tmp/ipykernel_2869/2933082444.py:1: RuntimeWarning: divide by zero encountered in log
  np.log(0)


np.float64(-inf)

In [ ]:
np.log(1)

np.float64(0.0)

In [ ]:
np.log(A1)

array([0.        , 1.38629436, 2.19722458])

In [ ]:
np.exp(A1)

array([2.71828183e+00, 5.45981500e+01, 8.10308393e+03])

In [ ]:
# statistical Function

In [ ]:
A2 = np.array([1,2,3,4,5])

In [ ]:
A2

array([1, 2, 3, 4, 5])

In [ ]:
np.mean(A2)

np.float64(3.0)

In [ ]:
np.median(A2)

np.float64(3.0)

In [ ]:
np.std(A2)

np.float64(1.4142135623730951)

In [ ]:
np.min(A2)

np.int64(1)

In [ ]:
np.max(A2)

np.int64(5)

In [ ]:
s1 = np.array([68,67,58,1003])

In [ ]:
s1

array([  68,   67,   58, 1003])

In [ ]:
np.mean(s1)

np.float64(299.0)

In [ ]:
np.median(s1)

np.float64(67.5)

In [ ]:
np.std(s1)

np.float64(406.47324635208156)

In [ ]:
np.min(s1)

np.int64(58)

In [ ]:
np.max(s1)

np.int64(1003)

In [ ]:
s2=np.array([[1,2],[3,4]])

In [ ]:
s2

array([[1, 2],
       [3, 4]])

In [ ]:
#Flattening

In [ ]:
s2.flatten()

array([1, 2, 3, 4])

In [ ]:
s3=np.array([[[34,56],[67,98]],[[23,67],[56,54]]])

In [ ]:
s3

array([[[34, 56],
        [67, 98]],

       [[23, 67],
        [56, 54]]])

In [ ]:
s3.flatten()

array([34, 56, 67, 98, 23, 67, 56, 54])

In [ ]:
a1=np.array([1,2])
a2=np.array([3,4])

In [ ]:
a1

array([1, 2])

In [ ]:
a2

array([3, 4])

In [ ]:
np.concatenate((a1,a2))

array([1, 2, 3, 4])

In [ ]:
A=np.array([1,2,3,4])

In [ ]:
A

array([0, 1, 2, 3, 4, 5])

In [ ]:
np.array_split(A,2)

[array([1, 2]), array([3, 4])]

In [ ]:
# Random Module

In [ ]:
np.random.rand(3)

array([0.01624499, 0.62967197, 0.65161899])

In [ ]:
np.random.rand(10)

array([0.77895059, 0.38126651, 0.26546184, 0.00631904, 0.78969081,
       0.65689534, 0.84746154, 0.84120795, 0.41160539, 0.34319213])

In [ ]:
np.random.randint(1,100,10)

array([50, 24, 55, 22, 31,  1, 75, 68, 86,  1])

In [ ]:
A=np.array([[74,89],[58,99]])

In [ ]:
A

array([[74, 89],
       [58, 99]])

In [ ]:
np.sum(A,axis=0)

array([132, 188])

In [ ]:
np.sum(A,axis=1)

array([163, 157])

In [ ]:
a1=np.array([1,np.nan,3])

In [ ]:
a1

array([ 1., nan,  3.])

In [ ]:
np.isnan(a1)

array([False,  True, False])

In [ ]:
a1=np.array([[23,np.nan],[34,np.nan]])

In [ ]:
a1

array([[23., nan],
       [34., nan]])

In [ ]:
np.isnan(a1)

array([[False,  True],
       [False,  True]])

In [ ]:
A=np.array([0,1,2,3,4,5])

In [ ]:
A

array([0, 1, 2, 3, 4, 5])

In [ ]:
reshaped= A.reshape(2,3)

In [ ]:
reshaped

array([[0, 1, 2],
       [3, 4, 5]])